version: '3.8'

services:
  api:
    container_name: bio-api
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ~/.deepface/weights:/root/.deepface/weights
    depends_on:
      - db
    environment:
      - PORT=5000
      - JWT_SECRET=${SECRET_KEY}
  db:
    container_name: bio-db
    image: "mongo:4.2.16-bionic"
    environment:  
      - MONGO_MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST_LOCAL=${MONGO_HOST_LOCAL}
    ports:
      - "27017:27017"
    volumes:
      - ./start.sh:/docker-entrypoint-initdb.d/start.sh
